version: '3.8'
 
services:
  # nodeapp:
  #   image: image-2
  #   container_name: nodecontainer
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     MONGO_DB_USERNAME: admin
  #     MONGO_DB_PWD: passward
  #   restart: unless-stopped
    
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - /home/ubuntu/mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017

