services:
  node-app:
    build: .
    container_name: nodejs-testapp
    ports:
    - "5050:5050"
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PWD: passward

    # volumes:
    # - .:/nodejs-testapp
    restart: unless-stopped
